---
title: "ZIKPI Komi Nyuiadzi"
subtitle: "Lomé – Togo / Tél : 00228 91 96 91 99 / E-mail : nyuiadzi@gmail.com"
format: html
---

## Compétences clés

o Appui-conseil en gouvernance et développement économique local ;

<p>

o Appui-conseil en stratégie financière et mobilisation des ressources locales ;

<p>

o Gestion de projets et d’activités programmatiques ;

<p>

o Conception de projet et mobilisation de ressources ;

<p>

o Planification prenant en compte les enjeux majeurs (genre/inclusion) ;

<p>

o Audit organisationnel et institutionnel des collectivités locales ;

<p>

o Gestion axée sur les résultats et approche changement ;

<p>

o Collecte, traitement et analyse de données.

## Profil

o BAC+5 en Economie, option aménagement du territoire et gestion des collectivités territoriales ;

<p>

o 15 ans d’expérience en matière de l’élaboration de stratégie financière, planification budgétaire, mobilisation et gestion des ressources financières collectivités territoriales ;

<p>

o 6 ans d’expériences en appui-accompagnement des collectivités territoriales en développement économique local ;

o 15 ans d’expérience professionnelle en préparation de proposition de projets/programmes en vue de la recherche de financement et plaidoyer auprès des bailleurs de fonds internationaux ;

o 6 ans d’expériences cumulées en tant que spécialiste en gestionnaire de projets ;

o 5 ans d’expériences cumulées en analyse de données socioéconomiques dans le cadre des diagnostics pour la territorialisation des ODD ;

o Excellente capacité en analyse, synthèse, rédaction de rapports techniques et de suivi ;

o 2 ans d’expériences en matière d’activités de gestion des connaissances et de capitalisation, notamment en appui à la mobilisation de ressources et la gestion financière des points d’eau ;

o Excellente capacité en gestion relationnelle avec les autorités publiques et les partenaires techniques et financiers ;

o Excellente maitrise du contexte togolais en matière de gouvernance et mise en œuvre de politiques de développement.

## Scolarité et diplômes

| Diplôme | Année | Institution | Lieu |
|------------------|------------------|------------------|------------------|
| DESS en Economie, **option** Aménagement du Territoire et Gestion des Collectivités Territoriales | 2008-2010 | Université de Lomé, Faculté des sciences économiques et de gestion (FASEG) | Lomé, Togo |
| Maîtrise en Sciences économiques | 2007-2008 | Université de Lomé, Faculté des sciences économiques et de gestion (FASEG) | Lomé, Togo |
| Licence en Sciences économiques | 2006-2007 | Université de Lomé, Faculté des sciences économiques et de gestion (FASEG) | Lomé, Togo |
| Baccalauréat série D | 2001-2002 | Collège protestant de Kpalimé | Kpalimé, Togo. |